---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: rate-limit
  labels:
    app.kubernetes.io/name: ratelimit
    app: ratelimit
data:
  httpbin-ratelimit.yaml: |
    domain: httpbin-ratelimit

    descriptors:
      - key: do_rate_limit
        value: "yes"
        descriptors:
        - key: PATH
          value: "/headers"
          rate_limit:
            unit: minute
            requests_per_unit: 10
            
      - key: PATH
        value: "/get"
        rate_limit:
          unit: minute
          requests_per_unit: 5
