---
apiVersion: v1
kind: Namespace
metadata:
  name: rate-limit
  labels:
    name: rate-limit
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: rate-limit
  labels:
    app.kubernetes.io/name: ratelimit
    app: ratelimit
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-debug
    port: 6070
    targetPort: 6070
    protocol: TCP
  selector:
    app.kubernetes.io/name: ratelimit
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: rate-limit
  labels:
    app.kubernetes.io/name: ratelimit
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: rate-limit
  labels:
    app.kubernetes.io/name: ratelimit
    app: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ratelimit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ratelimit
        app: ratelimit
    spec:
      containers:
        - name: ratelimit
          image: "envoyproxy/ratelimit:38500fe5"
          imagePullPolicy: IfNotPresent
          command: ["/bin/ratelimit"]
          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.memory

          - name: LOG_LEVEL
            value: debug
          - name: REDIS_SOCKET_TYPE
            value: tcp
          - name: REDIS_URL
            value: "redis-server.redis.svc.cluster.local:6379"
          - name: REDIS_HEALTH_CHECK_ACTIVE_CONNECTION
            value: "false"
          - name: USE_STATSD
            value: "false"
          - name: PROMETHEUS_ADDR
            value: ":9090"
          - name: PROMETHEUS_PATH
            value: "/metrics"
          - name: CONFIG_TYPE
            value: "FILE"
          - name: DISABLE_STATS
            value: "false"
          - name: USE_DOG_STATSD
            value: "false"
          - name: USE_PROMETHEUS
            value: "true"
          - name: FORCE_START_WITHOUT_INITIAL_CONFIG
            value: "true"
          - name: HOST
            value: "::"
          - name: GRPC_HOST
            value: "::"
          - name: RUNTIME_ROOT
            value: /data
          - name: RUNTIME_SUBDIRECTORY
            value: ratelimit
          - name: RUNTIME_WATCH_ROOT
            value: "false"
          - name: RUNTIME_IGNOREDOTFILES
            value: "true"
          ports:
          - containerPort: 8080
          - containerPort: 8081
          - containerPort: 6070
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 1024Mi
          volumeMounts:
          - name: config-volume
            mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-config
